require 'securerandom'

class DanmakuParser

  def initialize(danmaku_storage)
    @temp_storage = danmaku_storage
  end

  @content = <<END
[ScriptInfo]
; Script generated by DanmakuHunter v0.01,
; By Team SadTreeFriends,
; All rights reserved,
; http://sadtreefriends.github.io/

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment,
END

  @style_library = Hash.new{ |style, color| }



  File.open("output","w") do |f|
    f.write @content
  end

end